print("Charles McNeil")
cars = ['Ford', 'Chrysler', 'Dodge', 'Ram', 'Jeep', 'Chevy', 'GMC', 'Buick']
print(cars)
print(len(cars))
cars.append('Buick')
print(cars)
print(cars[3])
cars.insert(2, 'Toyota')
print(cars)
cars.pop(4)
print(cars)
cars.sort()
print(cars)
cars.sort(reverse=True)
print(cars)
my_array_length = len(cars)
array_string = 'The length of my array is '
print(array_string + str(my_array_length))
